server:
  port: 9000

spring:
  profiles:
    active: prod
  application:
    name: feishu-api
  main:
    allow-bean-definition-overriding: true

datasource:
  file:
    name: jdbc.properties
    path: 'classpath:'

logback:
  level: info